// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/shopspring/decimal"

const TableNameAgentReportConfigHistory = "agent_report_config_history"

// AgentReportConfigHistory mapped from table <agent_report_config_history>
type AgentReportConfigHistory struct {
	ID             int64           `gorm:"column:id;type:bigint(20);primaryKey;comment:主键ID" json:"id,string"`                                   // 主键ID
	AgentID        int64           `gorm:"column:agent_id;type:int(11);not null;comment:代理ID" json:"agentId"`                                    // 代理ID
	Agentname      string          `gorm:"column:agentname;type:varchar(32);not null;comment:代理名称" json:"agentname"`                             // 代理名称
	AgentLevel     int64           `gorm:"column:agent_level;type:tinyint(4);not null;default:1;comment:代理层级" json:"agentLevel"`                 // 代理层级
	RateSport      decimal.Decimal `gorm:"column:rate_sport;type:decimal(8,5);not null;default:0.00000;comment:厂商费率-体育" json:"rateSport"`        // 厂商费率-体育
	RateSlot       decimal.Decimal `gorm:"column:rate_slot;type:decimal(8,5);not null;default:0.00000;comment:厂商费率-老虎机" json:"rateSlot"`         // 厂商费率-老虎机
	RateReal       decimal.Decimal `gorm:"column:rate_real;type:decimal(8,5);not null;default:0.00000;comment:厂商费率-真人" json:"rateReal"`          // 厂商费率-真人
	RateMachine    decimal.Decimal `gorm:"column:rate_machine;type:decimal(8,5);not null;default:0.00000;comment:厂商费率-实体机" json:"rateMachine"`   // 厂商费率-实体机
	RateDeposit    decimal.Decimal `gorm:"column:rate_deposit;type:decimal(8,5);not null;default:0.00000;comment:存款费率" json:"rateDeposit"`       // 存款费率
	ExpiredAt      int64           `gorm:"column:expired_at;type:int(11);not null;comment:代理关系过期天数" json:"expiredAt"`                            // 代理关系过期天数
	Tag            int64           `gorm:"column:tag;type:tinyint(4);not null;comment:标记: 0-厂商费率, 1-佣金比例" json:"tag"`                            // 标记: 0-厂商费率, 1-佣金比例
	CreatedAt      int64           `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                                      // 创建时间
	CommissionRate decimal.Decimal `gorm:"column:commission_rate;type:decimal(8,5);not null;default:0.00000;comment:佣金比例" json:"commissionRate"` // 佣金比例
}

// TableName AgentReportConfigHistory's table name
func (*AgentReportConfigHistory) TableName() string {
	return TableNameAgentReportConfigHistory
}
