// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGameType = "game_type"

// GameType mapped from table <game_type>
type GameType struct {
	ID        int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:类型:1-体育 2-电子 3-真人 4-捕鱼 5-棋牌 6-电竞 7-彩票 8-动物 9-快速 10-技能 11-table game" json:"id,string"` // 类型:1-体育 2-电子 3-真人 4-捕鱼 5-棋牌 6-电竞 7-彩票 8-动物 9-快速 10-技能 11-table game
	Name      string `gorm:"column:name;type:varchar(64);not null;comment:自定类型名称" json:"name"`                                                                              // 自定类型名称
	Status    int64  `gorm:"column:status;type:tinyint(1);not null;comment:状态: 1-启用 0-停用" json:"status"`                                                                    // 状态: 1-启用 0-停用
	CreatedAt int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt int64  `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
	CreatedBy string `gorm:"column:created_by;type:varchar(30);comment:操作人姓名" json:"createdBy"` // 操作人姓名
	UpdatedBy string `gorm:"column:updated_by;type:varchar(30);comment:最后更新人" json:"updatedBy"` // 最后更新人
}

// TableName GameType's table name
func (*GameType) TableName() string {
	return TableNameGameType
}
