// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinAgentTopLine = "win_agent_top_line"

// WinAgentTopLine mapped from table <win_agent_top_line>
type WinAgentTopLine struct {
	ID           int64 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id,string"`
	TopAgentUID  int64 `gorm:"column:top_agent_uid;type:bigint;not null;comment:总代理" json:"topAgentUid"` // 总代理
	AgentLineUID int64 `gorm:"column:agent_line_uid;type:bigint;comment:代理线" json:"agentLineUid"`        // 代理线
	CreatedAt    int64 `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                          // 创建时间
}

// TableName WinAgentTopLine's table name
func (*WinAgentTopLine) TableName() string {
	return TableNameWinAgentTopLine
}
