// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinConfig = "win_config"

// WinConfig mapped from table <win_config>
type WinConfig struct {
	ID        int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	Title     string `gorm:"column:title;type:varchar(32);not null;comment:名字" json:"title"`                                  // 名字
	TitleZh   string `gorm:"column:title_zh;type:varchar(64);not null;comment:名字中文" json:"titleZh"`                           // 名字中文
	Value     string `gorm:"column:value;type:varchar(4096);not null;comment:字段值" json:"value"`                               // 字段值
	ShowApp   int64  `gorm:"column:show_app;type:tinyint;not null;default:1;comment:类型:0-全部 1-WEB 2-后台 3-不显示" json:"showApp"` // 类型:0-全部 1-WEB 2-后台 3-不显示
	CanModify int64  `gorm:"column:can_modify;type:tinyint;not null;default:1;comment:支持修改:1-支持 0-不支持" json:"canModify"`      // 支持修改:1-支持 0-不支持
	Status    int64  `gorm:"column:status;type:tinyint;not null;default:1;comment:是否启用:1-启用 0-不启用" json:"status"`             // 是否启用:1-启用 0-不启用
	CreatedAt int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`
	UpdatedAt int64  `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`
}

// TableName WinConfig's table name
func (*WinConfig) TableName() string {
	return TableNameWinConfig
}
