// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/shopspring/decimal"

const TableNameWinCheckInRecord = "win_check_in_record"

// WinCheckInRecord mapped from table <win_check_in_record>
type WinCheckInRecord struct {
	ID          int64           `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:主键" json:"id,string"`           // 主键
	PromotionID int64           `gorm:"column:promotion_id;type:int;not null;comment:签到活动ID" json:"promotionId"`                // 签到活动ID
	UserID      int64           `gorm:"column:user_id;type:int;not null;comment:客户表ID" json:"userId"`                           // 客户表ID
	Username    string          `gorm:"column:username;type:varchar(32);not null;comment:用户名" json:"username"`                  // 用户名
	SupUID      int64           `gorm:"column:sup_uid;type:int unsigned;not null;comment:上级代理ID" json:"supUid"`                 // 上级代理ID
	SupUsername string          `gorm:"column:sup_username;type:varchar(32);not null;comment:上级代理名" json:"supUsername"`         // 上级代理名
	Days        int64           `gorm:"column:days;type:smallint unsigned;not null;comment:连续签到天数" json:"days"`                 // 连续签到天数
	AwardAmount decimal.Decimal `gorm:"column:award_amount;type:decimal(15,4);not null;comment:签到奖励" json:"awardAmount"`        // 签到奖励
	AuditTimes  int64           `gorm:"column:audit_times;type:tinyint unsigned;not null;comment:稽核倍数" json:"auditTimes"`       // 稽核倍数
	Status      int64           `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:状态：1有效0无效" json:"status"` // 状态：1有效0无效
	CheckInAt   int64           `gorm:"column:check_in_at;type:int;not null;comment:领取时间" json:"checkInAt"`                     // 领取时间
}

// TableName WinCheckInRecord's table name
func (*WinCheckInRecord) TableName() string {
	return TableNameWinCheckInRecord
}
