// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinAgentTransferLog = "win_agent_transfer_log"

// WinAgentTransferLog mapped from table <win_agent_transfer_log>
type WinAgentTransferLog struct {
	ID            int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:ID" json:"id,string"`        // ID
	FromUID       int64  `gorm:"column:from_uid;type:int;not null;comment:转移代理" json:"fromUid"`                       // 转移代理
	FromUsername  string `gorm:"column:from_username;type:varchar(100);not null;comment:转移代理名" json:"fromUsername"`   // 转移代理名
	ToUID         int64  `gorm:"column:to_uid;type:int;not null;comment:转移到代理UID" json:"toUid"`                       // 转移到代理UID
	ToUsername    string `gorm:"column:to_username;type:varchar(100);not null;comment:转移到代理名" json:"toUsername"`      // 转移到代理名
	OperationID   int64  `gorm:"column:operation_id;type:int;not null;comment:操作人" json:"operationId"`                // 操作人
	OperationName string `gorm:"column:operation_name;type:varchar(100);not null;comment:操作人姓名" json:"operationName"` // 操作人姓名
	CreatedAt     int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                     // 创建时间
	UpdatedAt     int64  `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                     // 修改时间
}

// TableName WinAgentTransferLog's table name
func (*WinAgentTransferLog) TableName() string {
	return TableNameWinAgentTransferLog
}
