// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.skig.tech/zero-core/common/ent/predicate"
	"gitlab.skig.tech/zero-core/common/ent/winbetslip"
)

// WinBetslipQuery is the builder for querying WinBetslip entities.
type WinBetslipQuery struct {
	config
	ctx        *QueryContext
	order      []winbetslip.OrderOption
	inters     []Interceptor
	predicates []predicate.WinBetslip
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WinBetslipQuery builder.
func (wbq *WinBetslipQuery) Where(ps ...predicate.WinBetslip) *WinBetslipQuery {
	wbq.predicates = append(wbq.predicates, ps...)
	return wbq
}

// Limit the number of records to be returned by this query.
func (wbq *WinBetslipQuery) Limit(limit int) *WinBetslipQuery {
	wbq.ctx.Limit = &limit
	return wbq
}

// Offset to start from.
func (wbq *WinBetslipQuery) Offset(offset int) *WinBetslipQuery {
	wbq.ctx.Offset = &offset
	return wbq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wbq *WinBetslipQuery) Unique(unique bool) *WinBetslipQuery {
	wbq.ctx.Unique = &unique
	return wbq
}

// Order specifies how the records should be ordered.
func (wbq *WinBetslipQuery) Order(o ...winbetslip.OrderOption) *WinBetslipQuery {
	wbq.order = append(wbq.order, o...)
	return wbq
}

// First returns the first WinBetslip entity from the query.
// Returns a *NotFoundError when no WinBetslip was found.
func (wbq *WinBetslipQuery) First(ctx context.Context) (*WinBetslip, error) {
	nodes, err := wbq.Limit(1).All(setContextOp(ctx, wbq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{winbetslip.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wbq *WinBetslipQuery) FirstX(ctx context.Context) *WinBetslip {
	node, err := wbq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WinBetslip ID from the query.
// Returns a *NotFoundError when no WinBetslip ID was found.
func (wbq *WinBetslipQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wbq.Limit(1).IDs(setContextOp(ctx, wbq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{winbetslip.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wbq *WinBetslipQuery) FirstIDX(ctx context.Context) int {
	id, err := wbq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WinBetslip entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WinBetslip entity is found.
// Returns a *NotFoundError when no WinBetslip entities are found.
func (wbq *WinBetslipQuery) Only(ctx context.Context) (*WinBetslip, error) {
	nodes, err := wbq.Limit(2).All(setContextOp(ctx, wbq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{winbetslip.Label}
	default:
		return nil, &NotSingularError{winbetslip.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wbq *WinBetslipQuery) OnlyX(ctx context.Context) *WinBetslip {
	node, err := wbq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WinBetslip ID in the query.
// Returns a *NotSingularError when more than one WinBetslip ID is found.
// Returns a *NotFoundError when no entities are found.
func (wbq *WinBetslipQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wbq.Limit(2).IDs(setContextOp(ctx, wbq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{winbetslip.Label}
	default:
		err = &NotSingularError{winbetslip.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wbq *WinBetslipQuery) OnlyIDX(ctx context.Context) int {
	id, err := wbq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WinBetslips.
func (wbq *WinBetslipQuery) All(ctx context.Context) ([]*WinBetslip, error) {
	ctx = setContextOp(ctx, wbq.ctx, "All")
	if err := wbq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WinBetslip, *WinBetslipQuery]()
	return withInterceptors[[]*WinBetslip](ctx, wbq, qr, wbq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wbq *WinBetslipQuery) AllX(ctx context.Context) []*WinBetslip {
	nodes, err := wbq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WinBetslip IDs.
func (wbq *WinBetslipQuery) IDs(ctx context.Context) (ids []int, err error) {
	if wbq.ctx.Unique == nil && wbq.path != nil {
		wbq.Unique(true)
	}
	ctx = setContextOp(ctx, wbq.ctx, "IDs")
	if err = wbq.Select(winbetslip.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wbq *WinBetslipQuery) IDsX(ctx context.Context) []int {
	ids, err := wbq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wbq *WinBetslipQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wbq.ctx, "Count")
	if err := wbq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wbq, querierCount[*WinBetslipQuery](), wbq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wbq *WinBetslipQuery) CountX(ctx context.Context) int {
	count, err := wbq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wbq *WinBetslipQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wbq.ctx, "Exist")
	switch _, err := wbq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wbq *WinBetslipQuery) ExistX(ctx context.Context) bool {
	exist, err := wbq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WinBetslipQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wbq *WinBetslipQuery) Clone() *WinBetslipQuery {
	if wbq == nil {
		return nil
	}
	return &WinBetslipQuery{
		config:     wbq.config,
		ctx:        wbq.ctx.Clone(),
		order:      append([]winbetslip.OrderOption{}, wbq.order...),
		inters:     append([]Interceptor{}, wbq.inters...),
		predicates: append([]predicate.WinBetslip{}, wbq.predicates...),
		// clone intermediate query.
		sql:  wbq.sql.Clone(),
		path: wbq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RoundID string `json:"round_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WinBetslip.Query().
//		GroupBy(winbetslip.FieldRoundID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wbq *WinBetslipQuery) GroupBy(field string, fields ...string) *WinBetslipGroupBy {
	wbq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WinBetslipGroupBy{build: wbq}
	grbuild.flds = &wbq.ctx.Fields
	grbuild.label = winbetslip.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RoundID string `json:"round_id,omitempty"`
//	}
//
//	client.WinBetslip.Query().
//		Select(winbetslip.FieldRoundID).
//		Scan(ctx, &v)
func (wbq *WinBetslipQuery) Select(fields ...string) *WinBetslipSelect {
	wbq.ctx.Fields = append(wbq.ctx.Fields, fields...)
	sbuild := &WinBetslipSelect{WinBetslipQuery: wbq}
	sbuild.label = winbetslip.Label
	sbuild.flds, sbuild.scan = &wbq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WinBetslipSelect configured with the given aggregations.
func (wbq *WinBetslipQuery) Aggregate(fns ...AggregateFunc) *WinBetslipSelect {
	return wbq.Select().Aggregate(fns...)
}

func (wbq *WinBetslipQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wbq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wbq); err != nil {
				return err
			}
		}
	}
	for _, f := range wbq.ctx.Fields {
		if !winbetslip.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wbq.path != nil {
		prev, err := wbq.path(ctx)
		if err != nil {
			return err
		}
		wbq.sql = prev
	}
	return nil
}

func (wbq *WinBetslipQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WinBetslip, error) {
	var (
		nodes = []*WinBetslip{}
		_spec = wbq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WinBetslip).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WinBetslip{config: wbq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wbq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (wbq *WinBetslipQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wbq.querySpec()
	_spec.Node.Columns = wbq.ctx.Fields
	if len(wbq.ctx.Fields) > 0 {
		_spec.Unique = wbq.ctx.Unique != nil && *wbq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wbq.driver, _spec)
}

func (wbq *WinBetslipQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(winbetslip.Table, winbetslip.Columns, sqlgraph.NewFieldSpec(winbetslip.FieldID, field.TypeInt))
	_spec.From = wbq.sql
	if unique := wbq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wbq.path != nil {
		_spec.Unique = true
	}
	if fields := wbq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, winbetslip.FieldID)
		for i := range fields {
			if fields[i] != winbetslip.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wbq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wbq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wbq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wbq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wbq *WinBetslipQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wbq.driver.Dialect())
	t1 := builder.Table(winbetslip.Table)
	columns := wbq.ctx.Fields
	if len(columns) == 0 {
		columns = winbetslip.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wbq.sql != nil {
		selector = wbq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wbq.ctx.Unique != nil && *wbq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wbq.predicates {
		p(selector)
	}
	for _, p := range wbq.order {
		p(selector)
	}
	if offset := wbq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wbq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

func (wbq *WinBetslipQuery) SqlQuery(ctx context.Context) (r1 string, r2 []any) {
	builder := sql.Dialect(wbq.driver.Dialect())
	t1 := builder.Table(winbetslip.Table)
	columns := wbq.ctx.Fields
	if len(columns) == 0 {
		columns = winbetslip.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wbq.sql != nil {
		selector = wbq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wbq.ctx.Unique != nil && *wbq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wbq.predicates {
		p(selector)
	}
	for _, p := range wbq.order {
		p(selector)
	}
	if offset := wbq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wbq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	r1, r2 = selector.Query()
	//r3 = make([]*WinBetslip,0)

	return
}

// WinBetslipGroupBy is the group-by builder for WinBetslip entities.
type WinBetslipGroupBy struct {
	selector
	build *WinBetslipQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wbgb *WinBetslipGroupBy) Aggregate(fns ...AggregateFunc) *WinBetslipGroupBy {
	wbgb.fns = append(wbgb.fns, fns...)
	return wbgb
}

// Scan applies the selector query and scans the result into the given value.
func (wbgb *WinBetslipGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wbgb.build.ctx, "GroupBy")
	if err := wbgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WinBetslipQuery, *WinBetslipGroupBy](ctx, wbgb.build, wbgb, wbgb.build.inters, v)
}

func (wbgb *WinBetslipGroupBy) sqlScan(ctx context.Context, root *WinBetslipQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wbgb.fns))
	for _, fn := range wbgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wbgb.flds)+len(wbgb.fns))
		for _, f := range *wbgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wbgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wbgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WinBetslipSelect is the builder for selecting fields of WinBetslip entities.
type WinBetslipSelect struct {
	*WinBetslipQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wbs *WinBetslipSelect) Aggregate(fns ...AggregateFunc) *WinBetslipSelect {
	wbs.fns = append(wbs.fns, fns...)
	return wbs
}

// Scan applies the selector query and scans the result into the given value.
func (wbs *WinBetslipSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wbs.ctx, "Select")
	if err := wbs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WinBetslipQuery, *WinBetslipSelect](ctx, wbs.WinBetslipQuery, wbs, wbs.inters, v)
}

func (wbs *WinBetslipSelect) sqlScan(ctx context.Context, root *WinBetslipQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wbs.fns))
	for _, fn := range wbs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wbs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wbs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
