// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.skig.tech/zero-core/common/ent/predicate"
	"gitlab.skig.tech/zero-core/common/ent/wingamelist"
)

// WinGameListDelete is the builder for deleting a WinGameList entity.
type WinGameListDelete struct {
	config
	hooks    []Hook
	mutation *WinGameListMutation
}

// Where appends a list predicates to the WinGameListDelete builder.
func (wgld *WinGameListDelete) Where(ps ...predicate.WinGameList) *WinGameListDelete {
	wgld.mutation.Where(ps...)
	return wgld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wgld *WinGameListDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, wgld.sqlExec, wgld.mutation, wgld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (wgld *WinGameListDelete) ExecX(ctx context.Context) int {
	n, err := wgld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wgld *WinGameListDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(wingamelist.Table, sqlgraph.NewFieldSpec(wingamelist.FieldID, field.TypeInt32))
	if ps := wgld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wgld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	wgld.mutation.done = true
	return affected, err
}

// WinGameListDeleteOne is the builder for deleting a single WinGameList entity.
type WinGameListDeleteOne struct {
	wgld *WinGameListDelete
}

// Where appends a list predicates to the WinGameListDelete builder.
func (wgldo *WinGameListDeleteOne) Where(ps ...predicate.WinGameList) *WinGameListDeleteOne {
	wgldo.wgld.mutation.Where(ps...)
	return wgldo
}

// Exec executes the deletion query.
func (wgldo *WinGameListDeleteOne) Exec(ctx context.Context) error {
	n, err := wgldo.wgld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{wingamelist.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wgldo *WinGameListDeleteOne) ExecX(ctx context.Context) {
	if err := wgldo.Exec(ctx); err != nil {
		panic(err)
	}
}
