// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Common is the predicate function for common builders.
type Common func(*sql.Selector)

// WinBetslip is the predicate function for winbetslip builders.
type WinBetslip func(*sql.Selector)

// WinBetslipsDetail is the predicate function for winbetslipsdetail builders.
type WinBetslipsDetail func(*sql.Selector)

// WinCoinLog is the predicate function for wincoinlog builders.
type WinCoinLog func(*sql.Selector)

// WinConfig is the predicate function for winconfig builders.
type WinConfig func(*sql.Selector)

// WinDict is the predicate function for windict builders.
type WinDict func(*sql.Selector)

// WinDictItem is the predicate function for windictitem builders.
type WinDictItem func(*sql.Selector)

// WinGameList is the predicate function for wingamelist builders.
type WinGameList func(*sql.Selector)

// WinGameSlot is the predicate function for wingameslot builders.
type WinGameSlot func(*sql.Selector)

// WinPlatList is the predicate function for winplatlist builders.
type WinPlatList func(*sql.Selector)

// WinUser is the predicate function for winuser builders.
type WinUser func(*sql.Selector)

// WinUserWallet is the predicate function for winuserwallet builders.
type WinUserWallet func(*sql.Selector)
